#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_tg")

env_renderer = env_tg.Clone()

renderer_obj = []
env_renderer.add_source_files(renderer_obj, "*.cpp")

env.modules_sources += renderer_obj
