#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_tg")

env_linux_sandbox = env_tg.Clone()

linux_sandbox_obj = []
env_linux_sandbox.add_source_files(linux_sandbox_obj, "*.cpp")

env.modules_sources += linux_sandbox_obj
