#include "sandboxing.h"

#ifdef LINUXBSD_ENABLED
#include <seccomp.h>
#include <sys/prctl.h>
#include <signal.h>
#include <fstream>
#include <string>
#endif

#ifdef LINUXBSD_ENABLED
void handle_sigsys(int signum, siginfo_t *info, void *context) {
	uint32_t arch = seccomp_arch_native();
	char *syscall_name = seccomp_syscall_resolve_num_arch(arch, info->si_syscall);
	print_line(vformat("Disallowed syscall \"%s\" caught in sandbox", syscall_name));
}

Error Sandboxing::sandbox() {
	// While just banning dangerous syscalls could be much better for mantaining this library, I don't trust that I would be able to comprehensively list them
	// This list was generated by looking at the emitted syscalls from godot

	// Maybe would could limit this more? Surely some of these are used but not absoloutely required.
	const char *permitted_syscalls[] = {
		"access",
		"arch_prctl",
		"bind",
		"brk",
		"chdir",
		"clock_gettime",
		"clock_nanosleep",
		"clone",
		"clone3",
		"close",
		"connect",
		"dup",
		"dup3",
		"execve",
		"exit",
		"exit_group",
		"fadvise64",
		"fcntl",
		"flock",
		"fstat",
		"fstatfs",
		"ftruncate",
		"futex",
		"getcwd",
		"getdents64",
		"getegid",
		"geteuid",
		"getgid",
		"getpeername",
		"getpid",
		"getrandom",
		"getresgid",
		"getresuid",
		"getsockname",
		"getsockopt",
		"gettid",
		"gettimeofday",
		"getuid",
		"ioctl",
		"lseek",
		"lstat",
		"madvise",
		"memfd_create",
		"mkdir",
		"mmap",
		"mprotect",
		"mremap",
		"munmap",
		"newfstatat",
		"openat",
		"pipe2",
		"poll",
		"ppoll",
		"prctl",
		"pread64",
		"prlimit64",
		"pselect6",
		"read",
		"readlink",
		"recvfrom",
		"recvmsg",
		"rmdir",
		"rseq",
		"rt_sigaction",
		"rt_sigprocmask",
		"sched_get_priority_max",
		"sched_get_priority_min",
		"sched_getaffinity",
		"sched_setaffinity",
		"sched_setscheduler",
		"sched_yield",
		"sendmsg",
		"sendto",
		"set_robust_list",
		"set_tid_address",
		"setpriority",
		"setsockopt",
		"socket",
		"socketpair",
		"stat",
		"statfs",
		"symlink",
		"sysinfo",
		"umask",
		"uname",
		"unlink",
		"vfork",
		"wait4",
		"write",
		"writev"
	};

	// Set up the signal handler
	// Use auditd.service and SCMP_ACT_LOG to handle SIGSYS from other threads
    struct sigaction sa;
    sa.sa_sigaction = handle_sigsys;
    sa.sa_flags = SA_SIGINFO;
    sigaction(SIGSYS, &sa, nullptr);

	// Block ALL syscalls, we will punch holes in this.
	scmp_filter_ctx seccomp_ctx = seccomp_init(SCMP_ACT_TRAP);
	ERR_FAIL_COND_V_MSG(!seccomp_ctx, ERR_CANT_CREATE, "Unable to initialize seccomp");

	// Punch holes for every syscall we need.
	for (int i = 0; i < sizeof(permitted_syscalls) / sizeof(permitted_syscalls[0]); i++) {
		const char *syscall = permitted_syscalls[i];
		int err = seccomp_rule_add_exact(seccomp_ctx, SCMP_ACT_ALLOW, seccomp_syscall_resolve_name(syscall), 0);
		ERR_FAIL_COND_V_MSG(err, FAILED, "Unable to seccomp rule add " + String(syscall));
	}

	/* apply the composed filter */
	int err = seccomp_load(seccomp_ctx);
	ERR_FAIL_COND_V_MSG(err, FAILED, "Unable to seccomp load");

	/* release allocated context */
	seccomp_release(seccomp_ctx);

	err = prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0);
	ERR_FAIL_COND_V_MSG(err == -1, FAILED, "Unable to prctl PR_SET_NO_NEW_PRIVS");

	return OK;
}

#else
Error Sandboxing::sandbox() {
	return ERR_UNAVAILABLE;
}
#endif

Sandboxing::Sandboxing() {
}

Sandboxing::~Sandboxing() {
}
